[package]
name = "elfkit"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
byteorder = "1"
enum-primitive-derive = "0.1"
num-traits = "^0.1"
bitflags = { git = "https://github.com/rust-lang-nursery/bitflags.git" ,rev = "ec6ddd5" }


[dev_dependencies]
colored = "1"

