[package]
name = "elfkit"
version = "0.1.0"
authors = ["Arvid E. Picciani <aep@exys.org>"]

[dependencies]
byteorder = "1"
enum-primitive-derive = "0.1"
num-traits = "^0.1"
bitflags = "0"


[dev_dependencies]
colored = "1"

